/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface FReader {
        "controls": string[];
        "focused": boolean;
        "speakable": boolean;
    }
    interface VInput {
        "placeholder": string;
        "type": string;
    }
}
declare global {
    interface HTMLFReaderElement extends Components.FReader, HTMLStencilElement {
    }
    var HTMLFReaderElement: {
        prototype: HTMLFReaderElement;
        new (): HTMLFReaderElement;
    };
    interface HTMLVInputElement extends Components.VInput, HTMLStencilElement {
    }
    var HTMLVInputElement: {
        prototype: HTMLVInputElement;
        new (): HTMLVInputElement;
    };
    interface HTMLElementTagNameMap {
        "f-reader": HTMLFReaderElement;
        "v-input": HTMLVInputElement;
    }
}
declare namespace LocalJSX {
    interface FReader {
        "controls"?: string[];
        "focused"?: boolean;
        "speakable"?: boolean;
    }
    interface VInput {
        "placeholder"?: string;
        "type"?: string;
    }
    interface IntrinsicElements {
        "f-reader": FReader;
        "v-input": VInput;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "f-reader": LocalJSX.FReader & JSXBase.HTMLAttributes<HTMLFReaderElement>;
            "v-input": LocalJSX.VInput & JSXBase.HTMLAttributes<HTMLVInputElement>;
        }
    }
}
